### ISSUE TITLE
ajsonrpc.tests.test_manager fails

### ISSUE THREAD

**Issue by musfay** [pavlov99/ajsonrpc#19]
Running the tests on openSUSE Linux.
```
[   19s] + python3.6 -m unittest -v
[   19s] test_init (ajsonrpc.tests.test_core.TestJSONRPC20BatchRequest) ... ok
[   19s] test_init (ajsonrpc.tests.test_core.TestJSONRPC20BatchResponse) ... ok
[   19s] test_code_validation_not_number (ajsonrpc.tests.test_core.TestJSONRPC20Error) ... ok
[   19s] test_code_validation_valid_numeric (ajsonrpc.tests.test_core.TestJSONRPC20Error) ... ok
[   19s] test_could_not_change_code_message_predefined_errors (ajsonrpc.tests.test_core.TestJSONRPC20Error) ... ok
[   19s] test_data_validation_valid (ajsonrpc.tests.test_core.TestJSONRPC20Error) ... ok
[   19s] test_message_validation_not_str (ajsonrpc.tests.test_core.TestJSONRPC20Error) ... ok
[   19s] test_message_validation_valid_str (ajsonrpc.tests.test_core.TestJSONRPC20Error) ... ok
[   19s] test_body_validation (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_id_validation_invalid (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_id_validation_valid (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_method_validation_correct (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_method_validation_invalid_rpc_prefix (ajsonrpc.tests.test_core.TestJSONRPC20Request)
[   19s] Test method SHOULD NOT starts with rpc. ... ok
[   19s] test_method_validation_not_str (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_notification_conversion (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_notification_init (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_params_validation_dict (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_params_validation_invalid (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_params_validation_iterable (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_params_validation_list (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_params_validation_none (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_params_validation_tuple (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_request_args (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_request_kwargs (ajsonrpc.tests.test_core.TestJSONRPC20Request) ... ok
[   19s] test_set_body_error_correct_error_class (ajsonrpc.tests.test_core.TestJSONRPC20Response)
[   19s] Return error class matching pre-defined error codes. ... skipped 'TODO: Implement later'
[   19s] test_set_body_result_and_error (ajsonrpc.tests.test_core.TestJSONRPC20Response) ... ok
[   19s] test_set_valid_body (ajsonrpc.tests.test_core.TestJSONRPC20Response) ... ok
[   19s] test_valid_error (ajsonrpc.tests.test_core.TestJSONRPC20Response) ... ok
[   19s] test_valid_result (ajsonrpc.tests.test_core.TestJSONRPC20Response) ... ok
[   19s] test__getattr_function (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_add_dict (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_add_function (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_class (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_class_prefix (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_del_method (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_empty (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_init_from_dict (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_object (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_object_prefix (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] test_to_dict (ajsonrpc.tests.test_dispatcher.TestDispatcher) ... ok
[   19s] ajsonrpc.tests.test_manager (unittest.loader._FailedTest) ... ERROR
[   19s] 
[   19s] ======================================================================
[   19s] ERROR: ajsonrpc.tests.test_manager (unittest.loader._FailedTest)
[   19s] ----------------------------------------------------------------------
[   19s] ImportError: Failed to import test module: ajsonrpc.tests.test_manager
[   19s] Traceback (most recent call last):
[   19s]   File "/usr/lib64/python3.6/unittest/loader.py", line 428, in _find_test_path
[   19s]     module = self._get_module_from_name(name)
[   19s]   File "/usr/lib64/python3.6/unittest/loader.py", line 369, in _get_module_from_name
[   19s]     __import__(name)
[   19s]   File "/home/abuild/rpmbuild/BUILD/ajsonrpc-1.1.0/ajsonrpc/tests/test_manager.py", line 9, in <module>
[   19s]     class TestAsyncJSONRPCResponseManager(unittest.IsolatedAsyncioTestCase):
[   19s] AttributeError: module 'unittest' has no attribute 'IsolatedAsyncioTestCase'
[   19s] 
[   19s] 
[   19s] ----------------------------------------------------------------------
[   19s] Ran 41 tests in 0.006s
```

Full log can be found here:
https://build.opensuse.org/package/live_build_log/home:musfay:python/python-ajsonrpc/openSUSE_Tumbleweed/x86_64

**Comment by musfay** [comment]
Looks like there is no problem with this project.
[pytest issue](https://github.com/pytest-dev/pytest/issues/6924)
